### ISSUE TITLE
테두리 색깔 바꾸고 싶습니다. 

### ISSUE THREAD

**Issue by koreanraichu** [wisdomstar94/tistory-cyworld-minihompi-ui-skin#1]
오랜만에 중고딩때로 돌아간 것 같아서 좋네요... 싸이월드 되살아난것도 죽었나 접속 안되는데... 
테마 테두리 색깔을 바꿀 수 있었으면 좋겠습니다. 예전에도 도토리를 주고 사야 하긴 했지만 테두리 색깔을 바꿀 수 있었던 걸로 기억하는데... 

개인적으로 있었으면 좋겠긴 한데, 막 급한 이슈까지는 아니니까 천천히 추가하셔도 됩니다.

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.

말씀 주신 부분은 스킨 옵션에 primary color 색상 옵션을 추가해보았습니다. 
![image](https://github.com/user-attachments/assets/0cf53e3a-843d-4e40-8773-ec03964c33a0)

아래는 스킨 옵션 적용 후 사진입니다.
![image](https://github.com/user-attachments/assets/82c1d1ab-4387-4e22-a751-694b26d773ee)

이런걸 원하셨던게 맞으실까요? 해당 부분은 배포되었으니 [최신 버전](https://github.com/wisdomstar94/tistory-cyworld-minihompi-ui-skin/releases/latest)의 스킨으로 적용 후 한번 확인 부탁드리겠습니다~!

**Comment by koreanraichu** [comment]
크~ 감사합니다!

**Comment by wisdomstar94** [comment]
본 이슈는 종료하겠습니다! 또 다른 문의 및 건의사항이 있으시면 또 별도 이슈로 남겨주세요! 감사합니다~
